### ISSUE TITLE
Cannot upload files start with `@`

### ISSUE THREAD

**Issue by Thamaraiselvam** [dropbox/dropbox-sdk-php#58]
I have few files its name starts with @ for example 
@exampleImage.png

Any workaround for this issue?

**Comment by greg-db** [comment]
@Thamaraiselvam Can you elaborate on the issue you're running in to? I.e., please share the code and error you're getting. 

This seems to be working fine for me:

    $metadata = $client->uploadFile("/@test_58", dbx\WriteMode::add(), $fp, $size);

I'll take a look at the issue you're running in to, but I can't promise support or a solution as this SDK is deprecated, because it uses the deprecated API v1:

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

You should migrate to [API v2](https://www.dropbox.com/developers) as soon as possible.

**Comment by Thamaraiselvam** [comment]
I will upgrade it to v2
Thanks.
