### ISSUE TITLE
v1_retired

### ISSUE THREAD

**Issue by Krupaly2k** [dropbox/dropbox-sdk-php#59]
Hi,
V1 api is no longer working. Please provide me some alternative as it is not working on live site

**Comment by ketanshah79** [comment]
These are the two alternatives 
* https://github.com/kunalvarma05/dropbox-php-sdk
* https://github.com/Alorel/dropbox-v2-php

Problem is, we would need to revisit the code as the SDK api's are very different/incomplete.

Its such a shame that dropbox hasn't provided a working v2 SDK when they had time to get it sorted. 

I am a Dropbox Business Team account holder and my code has stopped working due to this when it should just have been updating the composer.json's package with latest version number.

**Comment by greg-db** [comment]
We don't have plans for an official PHP SDK for Dropbox API v2, but you can use a third party library:

https://www.dropbox.com/developers/documentation/communitysdks

Or, you can call the HTTPS endpoints themselves:

https://www.dropbox.com/developers/documentation/http/documentation

If you need more time to migrate your app to API v2, we can offer an extension for access to API v1. To request that, please open an API ticket with the relevant app key(s):

https://www.dropbox.com/developers/contact
